/*******************************************************************************************************************
* PROJECT:      ADS TRAINING
* DEVELOPER:    LUIS MANUEL RANGEL JR
* TABLE:        A_MEDICATIONS
* DATE:         02/23/2024
*******************************************************************************************************************/

/*******************************************************************************************************************
* NECESSARY SQL PARAMETERS FOR STARTING A PROJECT
*******************************************************************************************************************/
-- thses are things that will be required below.
-- THIS WILL TELL THE COMPUTER WHO CAN READ/WRITE TO THE DIRECTORY.
use role research;

-- THIS IS THE COMPUTER POWER;
use warehouse query_wh_large;

-- THIS IS SO i DON'T NEED TO BE TYPING THIS MULTIPLE TIMES BUT I AM STILL GOING TO DO THAT.
use database delivered_211;

/*******************************************************************************************************************
* BASE JOINING TABLE
*******************************************************************************************************************/
CREATE OR REPLACE TEMPORARY TABLE FINAL_TABLE AS
SELECT MAIN.PATIENT_ID, MAIN.INDEX_DATE, 'BL_12MO' AS RUN_ID FROM RESEARCH.GSK_CRSWNP.A_PATIENT_LMRJR AS MAIN
UNION ALL
SELECT MAIN.PATIENT_ID, MAIN.INDEX_DATE, 'BL_6MO' AS RUN_ID FROM RESEARCH.GSK_CRSWNP.A_PATIENT_LMRJR AS MAIN
UNION ALL
SELECT MAIN.PATIENT_ID, MAIN.INDEX_DATE, 'FU_6MO' AS RUN_ID FROM RESEARCH.GSK_CRSWNP.A_PATIENT_LMRJR AS MAIN;

/*******************************************************************************************************************
* SYMPTOMS
*******************************************************************************************************************/
-- GETTING MY PROCEDURES
CREATE OR REPLACE TEMPORARY TABLE PT1 AS
SELECT DISTINCT MAIN.PATIENT_ID
	,MAIN.INDEX_DATE
	,CASE
		WHEN BASE.NOTE_RECORDED_DATE IS NOT NULL AND (DATEADD(DAY, -12*30.4375, MAIN.INDEX_DATE) <= BASE.NOTE_RECORDED_DATE AND BASE.NOTE_RECORDED_DATE < DATEADD(DAY, -6*30.4375, MAIN.INDEX_DATE)) THEN 'BL_12MO'
		WHEN BASE.NOTE_RECORDED_DATE IS NOT NULL AND (DATEADD(DAY, -6*30.4375, MAIN.INDEX_DATE) <= BASE.NOTE_RECORDED_DATE AND BASE.NOTE_RECORDED_DATE <= MAIN.INDEX_DATE) THEN 'BL_6MO'
		WHEN BASE.NOTE_RECORDED_DATE IS NOT NULL AND (MAIN.INDEX_DATE < BASE.NOTE_RECORDED_DATE AND BASE.NOTE_RECORDED_DATE <= DATEADD(DAY, 6*30.4375, (DATEADD(DAY, 1, MAIN.INDEX_DATE)))) THEN 'FU_6MO'
		ELSE 'NO DATA'
	END AS RUN_ID
	,COUNT(DISTINCT CASE WHEN (CONTAINS(REGEXP_REPLACE(UPPER(BASE.EXTRACTION), '\\s+', ''), 'FACEPAIN')
		 					OR CONTAINS(REGEXP_REPLACE(UPPER(BASE.EXTRACTION), '\\s+', ''), 'FACIALPAIN')
		 					OR CONTAINS(REGEXP_REPLACE(UPPER(BASE.EXTRACTION), '\\s+', ''), 'FACEPRESSURE')
		 					OR CONTAINS(REGEXP_REPLACE(UPPER(BASE.EXTRACTION), '\\s+', ''), 'FACIALPRESSURE')) THEN BASE.NOTE_RECORDED_DATE ELSE NULL END) AS FACIAL_PAIN
	,COUNT(DISTINCT CASE WHEN (CONTAINS(UPPER(BASE.EXTRACTION), 'NASAL')
		 						AND CONTAINS(UPPER(BASE.EXTRACTION), 'OBSTRUCTION')) THEN BASE.NOTE_RECORDED_DATE ELSE NULL END) AS NASAL_OBSTR
	,COUNT(DISTINCT CASE WHEN (CONTAINS(UPPER(BASE.EXTRACTION), 'NASAL')
		 						AND CONTAINS(UPPER(BASE.EXTRACTION), 'DISCHARGE')) THEN BASE.NOTE_RECORDED_DATE ELSE NULL END) AS NASAL_DISCHR
	,COUNT(DISTINCT CASE WHEN (CONTAINS(UPPER(BASE.EXTRACTION), 'ANOSMIA')
		 						OR CONTAINS(REGEXP_REPLACE(UPPER(BASE.EXTRACTION), '\\s+', ''), 'LOSSOFSENSEOFSMELL')) THEN BASE.NOTE_RECORDED_DATE ELSE NULL END) AS ANOSMIA
FROM RESEARCH.GSK_CRSWNP.A_PATIENT_LMRJR AS MAIN
LEFT JOIN RAW_EXTRACTIONS_DEIDPROD.CRS_SYMPTOMS_D216_20240227.CRS_SYMPTOMS_COMBINED_RESULTS AS BASE ON MAIN.PATIENT_ID=BASE.BOC_PATIENT_ID
GROUP BY 1,2,3;

/*******************************************************************************************************************
* PUTTING IT ALL TOGETHER
* MAKING SURE EACH TIME POINT HAS A VALUE
*******************************************************************************************************************/
CREATE OR REPLACE TABLE RESEARCH.GSK_CRSWNP.A_SYMPTOMS_LMRJR AS
SELECT MAIN.PATIENT_ID
				,MAIN.INDEX_DATE
				,MAIN.RUN_ID
				,CASE WHEN FTA.FACIAL_PAIN IS NULL THEN 0 ELSE FTA.FACIAL_PAIN END AS FACIAL_PAIN
				,CASE WHEN FTA.NASAL_OBSTR IS NULL THEN 0 ELSE FTA.NASAL_OBSTR END AS NASAL_OBSTR
				,CASE WHEN FTA.NASAL_DISCHR IS NULL THEN 0 ELSE FTA.NASAL_DISCHR END AS NASAL_DISCHR
				,CASE WHEN FTA.ANOSMIA IS NULL THEN 0 ELSE FTA.ANOSMIA END AS ANOSMIA
FROM FINAL_TABLE AS MAIN
LEFT JOIN PT1 AS FTA ON MAIN.PATIENT_ID=FTA.PATIENT_ID AND MAIN.INDEX_DATE=FTA.INDEX_DATE AND MAIN.RUN_ID=FTA.RUN_ID;